[backend]
db_url = "sqlite://db.sqlite3"
rest_check = "20s"

[dtnd]
host = "http://127.0.0.1"
port = 3000
node_id = "dtn://n1/"
rest_path = ""
ws_path = "/ws"
multi_user = false

[backoff]
initial_wait = 0.1
max_retries = 20
reconnection_pause = 300
constant_wait = 0.75

[bundles]
lifetime = "1s"  # check backend README for formatting rules
delivery_notification = false
compress_body = true

[usenet]
expiry_time = "28d"  # check backend README for formatting rules, 0 for no expiry
email = "t.e.schmitt@posteo.de"
newsgroups = [
    "monntpy.dev",
    "monntpy.offtopic",
    "monntpy.users.tu-darmstadt",
    "monntpy.users.uni-frankfurt",
    "monntpy.users.jlu-giessen",
]

[janitor]
# duration between janitor runs. 0 switches janitor off.
sleep = "5m"
