[dtnd]
host = "http://127.0.0.1"
port = 3000

node_id = ""
rest_path = ""
ws_path = "/ws"

[backoff]
initial_wait = 0.1
max_retries = 20
reconn_pause = 300
constant_wait = 0.75

[bundles]
lifetime = 86400000
deliv_notification = true

[usenet]
newsgroups = [
    "germany.hessen.darmstadt.darmstadt",
    "germany.hessen.darmstadt-dieburg.dieburg",
    "germany.hessen.darmstadt-dieburg.rossdorf"
]
