[backend]
db_url = "sqlite://db.sqlite3"

[dtnd]
host = "http://127.0.0.1"
port = 3000
node_id = "dtn://florentin/"
rest_path = ""
ws_path = "/ws"
multi_user = false

[backoff]
initial_wait = 0.1
max_retries = 20
reconn_pause = 300
constant_wait = 0.75

[bundles]
lifetime = 86400000
delivery_notification = false
compress_body = true

[usenet]
expiry_time = 86400000   # ms make human readable
email = "t.e.schmitt@posteo.de"
newsgroups = [
    "monntpy.dev",
    "monntpy.offtopic",
    "monntpy.users.tu-darmstadt",
    "monntpy.users.uni-frankfurt",
    "monntpy.users.jlu-giessen",
]
